version: "3"

services:

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=organization_catalog
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432

  fdk-nginx-enhetsregisteret-proxy-mock:
    image: ghcr.io/informasjonsforvaltning/fdk-nginx-enhetsregisteret-proxy-mock:staging_latest
    ports:
      - 8132:8080
