version: "3"

services:
  organization-catalogue:
    image: brreg/organization-catalogue:latest
    depends_on:
      - mongodb
    restart: always
    environment:
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=admin
      - MONGO_HOST=mongodb:27017
    ports:
      - 8140:8080
