version: "3.5"

services:
  publisher:
    image: brreg/publishers-api:latest
    depends_on:
      - mongodb
    restart: always
    environment:
      - PUBAPI_MONGO_USERNAME
      - PUBAPI_MONGO_PASSWORD
    ports:
      - 8080:8080

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$PUBAPI_MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$PUBAPI_MONGO_PASSWORD
    ports:
      - 27017:27017
