version: "3"

services:

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017

  fdk-nginx-enhetsregisteret-proxy-mock:
    image: eu.gcr.io/digdir-fdk-infra/fdk-nginx-enhetsregisteret-proxy-mock:latest
    ports:
      - 8132:8080

  sso:
    image: docker.pkg.github.com/informasjonsforvaltning/auth-utils-java/auth-utils-java:latest
    ports:
      - 8084:8084