version: "3"

services:
  organization-catalogue:
    image: eu.gcr.io/fdk-infra/organization-catalogue:latest
    depends_on:
      - mongodb
    restart: always
    environment:
      - MONGO_USERNAME
      - MONGO_PASSWORD
      - ENHETSREGISTERET_PROXY_URL
    ports:
      - 8140:8080

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017

  fdk-nginx-enhetsregisteret-proxy-mock:
    image: eu.gcr.io/fdk-infra/fdk-nginx-enhetsregisteret-proxy-mock:latest
    ports:
      - "8080:8080"
