version: "3"

services:
  organization-catalogue:
    image: brreg/organization-catalogue:latest
    depends_on:
      - mongodb
    restart: always
    environment:
      - PUBAPI_MONGO_USERNAME
      - PUBAPI_MONGO_PASSWORD
    ports:
      - 8080:8080
