version: "3"

services:
  organization-catalogue:
    image: brreg/organization-catalogue:latest
    depends_on:
      - mongodb
    restart: always
    environment:
      - PUBAPI_MONGO_USERNAME=admin
      - PUBAPI_MONGO_PASSWORD=admin
    ports:
      - 8080:8080

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
