version: "3"

services:
  organization-catalogue:
    build: ../organization-catalogue
    depends_on:
      - mongodb
    restart: always
    environment:
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=admin
      - ENHETSREGISTERET_PROXY_URL=http://fdk-nginx-enhetsregisteret-proxy-mock:8080/enhetsregisteret/api/enheter/
    ports:
      - 8140:8080
