version: "3"

services:
  organization-catalogue:
    image: brreg/organization-catalogue:latest
    depends_on:
      - mongodb
    restart: always
    environment:
      - PUBAPI_MONGO_USERNAME=admin
      - PUBAPI_MONGO_PASSWORD=admin
    ports:
      - 8140:8080
