version: "3.5"

services:
  publisher:
    image: brreg/organization-catalogue:latest
    depends_on:
      - mongodb
    restart: always
    environment:
      - ORGCAT_MONGO_USERNAME
      - ORGCAT_MONGO_PASSWORD
    ports:
      - 8080:8080

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$ORGCAT_MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$ORGCAT_MONGO_PASSWORD
    ports:
      - 27017:27017
