openapi: 3.0.2
info:
  description: Exposes a basic service which provides information related to the publishers of content in the National Data Directory
  version: '1.0'
  title: National Data Directory Publisher API
  termsOfService: 'https://fellesdatakatalog.brreg.no/about'
  contact:
    name: Brønnøysundregistrene
    url: 'https://fellesdatakatalog.brreg.no'
    email: fellesdatakatalog@brreg.no
  license:
    name: License of API
    url: 'http://data.norge.no/nlod/no/2.0'
externalDocs:
  description: Dokumentasjon på Informasjonsforvaltning GitHub
  url: https://informasjonsforvaltning.github.io/felles-datakatalog/datasett-katalog/api/
tags:
  - name: publisher
    description: Publisher Service
servers:
  - url: 'https://fellesdatakatalog.brreg.no'
paths:
  /publishers:
    get:
      tags:
        - publisher
      summary: Query for publishers.
      description: Returns a collection of matching publishers
      operationId: getPublishers
      parameters:
        - name: q
          in: query
          description: A query string to match a publisher name
          required: false
          schema:
            type: string
        - name: hierarchy
          in: query
          description: If you want the publishers arranged as a hierarchy
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Publisher'
        '404':
          description: Not Found
  /publishers/{id}:
    get:
      tags:
        - publisher
      description: Get a specific publisher by id
      operationId: getPublisherById
      parameters:
        - name: id
          in: path
          description: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConceptDocument"
        '404':
          description: Not Found
components:
  schemas:
    Publisher:
        type: object
        description: A publisher of content in FDK [dct:publisher]
        properties:
          id:
            type: string
            description: system-generated id (GUID)
          uri:
            type: string
            description: Link to the organization entry in The Brønnøysund Register Centre
          organizationId:
            type: string
            description: Organization number
          name:
            type: string
            description: The name of the organization as given in the The Brønnøysund Register Centre
          orgPath:
            type: string
          prefLabel:
            $ref: "#/components/schemas/PrefLabel"
    PrefLabel:
      type: object
      description:
        Preferred label [skosxl:prefLabel]
      properties:
        nb:
          type: string
          description:
            Preferred label [skosxl:prefLabel] in Norwegian Bokmål
