logging.level:
  root: WARN
  no: ${LOG_LEVEL:INFO}
  org.springframework: WARN
  org.springframework.web: WARN

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:5432/${POSTGRESQL_DB}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

  security.oauth2.resourceserver.jwt:
    jwk-set-uri: ${KEYCLOAK_OIDC_ISSUER:https://auth.staging.fellesdatakatalog.digdir.no/realms/fdk}/protocol/openid-connect/certs
    issuer-uri: ${KEYCLOAK_OIDC_ISSUER:https://auth.staging.fellesdatakatalog.digdir.no/realms/fdk}

application:
  enturDataUrl: ${ENTUR_TRANSMODEL_URL}
  enturHeaderKey: ${ENTUR_HEADER_KEY}
  enturHeaderValue: ${ENTUR_HEADER_VALUE}
  enhetsregisteretUrl: ${ENHETSREGISTERET_URL:https://data.brreg.no/enhetsregisteret/api/enheter/}
  enhetsregisteretHtmlUrl: ${ENHETSREGISTERET_HTML_URL:https://data.brreg.no/enhetsregisteret/oppslag/enheter/}
  enhetsregisteretProxyUrl: ${ENHETSREGISTERET_PROXY_BASE_URL:http://fdk-nginx-enhetsregisteret-proxy:8080}/enhetsregisteret/api
  organizationCatalogUrl: ${ORGANIZATION_CATALOG_HOST:https://organization-catalog.fellesdatakatalog.brreg.no}/organizations/
  municipalityUrl: ${GEONORGE_MUNICIPALITY_URL:https://data.geonorge.no/administrativeEnheter/kommune/id/}
  testOrganizations: 555111290,568843537,910131028,910244132,910258028,910298062,910888447,911259583,911527170,916285515,973633449
  defaultOrgPath: /ANNET/
  cors.originPatterns: ${CORS_ORIGIN_PATTERNS}

server.port: 8080

---
spring:
  config.activate.on-profile: develop
  datasource:
    url: jdbc:postgresql://localhost:5432/organization_catalog
    username: admin
    password: admin

application:
  enhetsregisteretUrl: https://data.brreg.no/enhetsregisteret/api/enheter/
  enhetsregisteretHtmlUrl: https://data.brreg.no/enhetsregisteret/oppslag/enheter/
  enhetsregisteretProxyUrl: http://localhost:8132/enhetsregisteret/api
  organizationCatalogUrl: http://localhost:8140/organizations/
  municipalityUrl: https://data.geonorge.no/administrativeEnheter/kommune/id/
  testOrganizations: 555111290,568843537,910131028,910244132,910258028,910298062,910888447,911259583,911527170,916285515,973633449
  cors.originPatterns: "*"

server.port: 8140

---
spring:
  config.activate.on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/organization_catalog
    username: testuser
    password: testpassword
  security.oauth2.resourceserver.jwt:
    jwk-set-uri: http://localhost:5050/auth/realms/fdk/protocol/openid-connect/certs
    issuer-uri: http://localhost:5050/auth/realms/fdk

application:
  enturDataUrl: http://localhost:5050/agreements/v1/adapter/transmodel/export
  enturHeaderKey: Header-Key
  enturHeaderValue: test
  enhetsregisteretUrl: http://localhost:5050/enhetsregisteret/api/enheter/
  enhetsregisteretHtmlUrl: http://localhost:5050/enhetsregisteret/oppslag/enheter/
  enhetsregisteretProxyUrl: http://localhost:5050/enhetsregisteret/api
  organizationCatalogUrl: http://localhost:5050/organizations/
  municipalityUrl: http://localhost:5050/administrativeEnheter/kommune/id/
  testOrganizations: 555111290,568843537,910131028,910244132,910258028,910298062,910888447,911259583,911527170,916285515,973633449
  cors.originPatterns: "*"
