---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - organization-catalog-deployment.yaml
  - organization-catalog-service.yaml
images:
  - name: organization-catalog
    newName: eu.gcr.io/digdir-fdk-infra/organization-catalog
    newTag: $(GIT_COMMIT_SHA)
