apiVersion: v1
kind: Service
metadata:
  labels:
    fdk.service: organization-catalog
  name: organization-catalog
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    fdk.service: organization-catalog
