name: Deploy to staging

on:
  pull_request:
    types: [ ready_for_review, opened, reopened, synchronize ]
    branches:
      - main

jobs:
  build-organization-catalog:
    name: Build when pull request is created
    if: github.event.pull_request.draft == false
    uses: Informasjonsforvaltning/workflows/.github/workflows/build-push.yaml@main
    with:
      app_name: organization-catalog
      java_version: '21'
      coverage_file_path: ./target/site/jacoco/jacoco.xml
      environment: staging
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GCP_SA_DIGDIR_FDK_GCR_KEY: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_KEY }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    name: Deploy to staging environment
    if: ${{ github.actor != 'dependabot[bot]' && github.event.pull_request.draft == false }}
    needs: [ build-organization-catalog ]
    uses: Informasjonsforvaltning/workflows/.github/workflows/kustomize-deploy.yaml@main
    with:
      app_name: organization-catalog
      environment: staging
      cluster: digdir-fdk-dev
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  dependabot-build:
    name: Build image on PR from dependabot
    if: ${{ github.actor == 'dependabot[bot]' }}
    uses: Informasjonsforvaltning/workflows/.github/workflows/build.yaml@main
    with:
      java_version: '21'
