name: Build and deploy to staging from feature branch on pull request

on:
  - pull_request

jobs:
  build-and-deploy-staging:
    name: Build, publish and deploy to staging environment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.GCP_SA_FDK_JENKINS_GCR_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_FDK_JENKINS_GCR }}

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: gcloud auth configure-docker

      - name: Build Docker image with GitHub commit sha tag
        run: docker build --build-arg JAR_FILE=organization-catalogue-1.0.0-SNAPSHOT.jar -t eu.gcr.io/fdk-infra/organization-catalogue:$GITHUB_SHA .

      - name: Publish docker image to Google Cloud
        run: docker -- push eu.gcr.io/fdk-infra/organization-catalogue:$GITHUB_SHA

      - name: Apply Helm template
        uses: stefanprodan/kube-tools@v1
        with:
          helm: 2.14.3
          command: |
            helm init --client-only
            helm repo add fdk https://informasjonsforvaltning.github.io/helm-chart/
            helm fetch --untar --untardir ./helm fdk/organization-catalogue
            helm template --set DOCKER_IMAGE_NAME="eu.gcr.io/fdk-infra/organization-catalogue:$GITHUB_SHA" -f ./helm/organization-catalogue/values/staging.yaml ./helm/organization-catalogue/ > ./kubectlapply.yaml
            cat ./kubectlapply.yaml
            chmod o+w ./kubectlapply.yaml
            cat kubectlapply.yaml

      - name: Get kubeconfig file from GKE
        uses: machine-learning-apps/gke-kubeconfig@master
        with:
          application_credentials: ${{ secrets.FDK_DEV_AUTODEPLOY }}
          project_id: fdk-dev
          location_zone: europe-north1-a
          cluster_name: fdk-dev

      - name: Deploy to staging
        uses: docker://bitnami/kubectl:latest
        env:
          KUBECONFIG: '/github/workspace/.kube/config'
        with:
          args: "apply -f ./kubectlapply.yaml --force"